#!/usr/bin/env python
"""Freeze sw2robot into a standalone executable with PyInstaller.

Builds a single-file binary for the host OS:
  * Windows -> ``sw2robot-web.exe`` (the only OS where the SolidWorks ``extract``
    step works -- it drives SolidWorks over COM via pywin32).
  * macOS / Linux -> ``sw2robot-web`` (no extension).  These cannot extract
    (no SolidWorks/COM), but view / edit / build / export -- including the
    URDF-input editing mode -- all work.

Why PyInstaller: this app stacks pywin32 COM (SolidWorks), numpy, trimesh and
pydantic (compiled pydantic_core) -- PyInstaller ships working hooks for all of
them, which Nuitka / cx_Freeze do not out of the box.  PyInstaller cannot
cross-compile, so each OS/arch is built on its own native runner.

Run it through uv so PyInstaller is available without polluting the project env::

    uv run --with pyinstaller python build_exe.py            # full web editor, one-file
    uv run --with pyinstaller python build_exe.py --target export
    uv run --with pyinstaller python build_exe.py --onedir   # faster start, a folder
    uv run --with pyinstaller python build_exe.py --lean     # base exe, no optional backends

The default build is the FULL-FEATURE editor: it bundles the optional runtime
backends the editor/CLI can reach -- skrobot+fcl (live self-collision + auto
joint-limits) and coacd (CoACD collision decomposition).  --lean drops them for
a smaller binary; --with-viser also bundles the standalone viser GUI.

Targets (entry points, mirroring [project.scripts] in pyproject.toml):
    web     sw2robot-web  -> the browser editor server (default; does
                             extract + build + edit + export + view)
    export  sw2urdf       -> the extract+build CLI
    cli     sw2robot      -> the headless build/edit/export CLI

On Windows the .exe still needs SolidWorks INSTALLED on the target machine -- it
drives SolidWorks over COM; it does not (and cannot) embed it.  The makepy
typelib wrappers are generated on first extract into %TEMP%\\sw2robot_gen_py
(see the runtime hook below), so no COM cache has to be pre-baked into the
bundle.  The COM hidden-imports + runtime hook are Windows-only; on macOS/Linux
pywin32 is absent, so they are skipped.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
IS_WINDOWS = sys.platform == "win32"
IS_MACOS = sys.platform == "darwin"

# entry-point shims: PyInstaller wants a script, not a ``module:func`` spec, so
# we generate a tiny launcher that imports the package entry and calls main().
TARGETS = {
    "web":    ("sw2robot-web", "sw2robot.editor.webserver"),
    "export": ("sw2urdf",      "sw2robot.exporter.export"),
    "cli":    ("sw2robot",     "sw2robot.editor.cli"),
}

# pywin32 pieces PyInstaller's static analysis misses (COM + the makepy code
# generator that runs at extract time).
WIN32_HIDDEN = [
    "pythoncom", "pywintypes",
    "win32com", "win32com.client", "win32com.client.gencache",
    "win32com.client.makepy", "win32com.client.genpy",
    "win32com.client.build", "win32com.client.dynamic",
    "win32api", "win32con", "win32timezone",
]

# Optional feature backends, named by IMPORT name (what PyInstaller --collect-all
# wants); pyproject lists the matching DIST names per extra:
#   EDITOR_UI -> [ui]  scikit-robot + python-fcl  (live self-collision + auto
#                      joint-limit sweep in the web editor)
#   COACD     -> [coacd]  CoACD convex decomposition (--collision coacd / the web
#                      "CoACD collision" box)
#   STANDALONE_UI -> [ui]  the standalone viser GUI -- a SEPARATE entry point, not
#                      reachable from the web/cli/export exe targets
EDITOR_UI_PACKAGES = ["skrobot", "fcl"]
COACD_PACKAGES = ["coacd"]
STANDALONE_UI_PACKAGES = ["viser"]
# The frozen exe is the FULL-FEATURE distribution: every optional backend the
# web editor / CLI can actually reach at runtime is bundled by default (the user
# cannot ``pip install`` into a frozen binary, so anything not bundled is dead
# there).  viser is excluded -- no exe entry point reaches it -- unless asked for.
FULL_FEATURE_PACKAGES = EDITOR_UI_PACKAGES + COACD_PACKAGES
ALL_OPTIONAL_PACKAGES = EDITOR_UI_PACKAGES + COACD_PACKAGES + STANDALONE_UI_PACKAGES
# never needed at runtime -- dropping them shaves size / avoids hook noise
BASE_EXCLUDES = ["tkinter", "matplotlib", "pytest", "IPython", "notebook",
                 "jupyter", "PyQt5", "PyQt6", "PySide2", "PySide6"]

# Redirect pywin32's makepy/gencache output to a WRITABLE dir: inside a frozen
# bundle the default gen_py path is the read-only _MEIPASS, which makes
# EnsureModule/EnsureDispatch raise on the first SolidWorks extract.
RTHOOK = '''\
# AUTO-GENERATED by build_exe.py -- do not edit.
import os
import sys
import tempfile

if getattr(sys, "frozen", False):
    _gen = os.path.join(tempfile.gettempdir(), "sw2robot_gen_py")
    try:
        os.makedirs(_gen, exist_ok=True)
        import win32com
        win32com.__gen_path__ = _gen
        win32com.__build_path__ = _gen
        # if gen_py was already imported its __path__ still points at the old
        # (read-only) location -- repoint it so generated submodules are found
        if "win32com.gen_py" in sys.modules:
            sys.modules["win32com.gen_py"].__path__ = [_gen]
        import win32com.client.gencache as _gc
        _gc.is_readonly = False
        try:
            _gc.GetGeneratePath()      # create the package + __init__ if absent
        except Exception:
            pass
    except Exception:
        pass
'''


def _write(path: str, text: str) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--target", choices=list(TARGETS), default="web",
                    help="which entry point to freeze (default: web)")
    ap.add_argument("--onedir", action="store_true",
                    help="emit a folder instead of a single .exe (faster start, "
                         "more reliable for the COM/makepy path)")
    ap.add_argument("--lean", action="store_true",
                    help="base build: skip the optional runtime backends "
                         "(skrobot/fcl self-collision + auto joint-limits, coacd "
                         "collision decomposition).  The default exe is the "
                         "FULL-FEATURE build and bundles them.")
    ap.add_argument("--with-viser", action="store_true",
                    help="also bundle the standalone viser GUI (a separate entry "
                         "point, not reached by the web/cli exe; off by default)")
    ap.add_argument("--windowed", action="store_true",
                    help="no console window (default keeps the console so the "
                         "server URL / logs are visible; on macOS the build is "
                         "always a windowed .app -- see --console-app)")
    ap.add_argument("--console-app", action="store_true",
                    help="macOS only: build a bare console binary instead of a "
                         "windowed .app (no Finder/Dock icon, but a "
                         "double-click opens Terminal with the logs)")
    ap.add_argument("--name", default=None,
                    help="override the output binary name")
    ap.add_argument("--icon", default=None,
                    help="path to an icon (Windows .ico / macOS .icns); default: "
                         "assets/icon.ico on Windows, assets/icon.icns on macOS")
    ap.add_argument("--clean", action="store_true",
                    help="wipe the PyInstaller cache before building")
    args = ap.parse_args()

    try:
        import PyInstaller.__main__ as pyi
    except ModuleNotFoundError:
        print("PyInstaller is not installed in this interpreter.\n"
              "Run instead:\n"
              "    uv run --with pyinstaller python build_exe.py "
              + " ".join(sys.argv[1:]), file=sys.stderr)
        return 2

    exe_name, module = TARGETS[args.target]
    exe_name = args.name or exe_name

    build_dir = os.path.join(ROOT, "build", "_pyi")
    shim = _write(os.path.join(build_dir, f"_entry_{args.target}.py"),
                  f"from {module} import main\n\n"
                  f"if __name__ == '__main__':\n    main()\n")

    web = os.path.join(ROOT, "sw2robot", "editor", "web", "index.html")

    # On macOS an embedded app icon only attaches to a windowed .app bundle, not
    # to a bare console executable (PyInstaller emits the .app only with
    # --windowed).  So default macOS to windowed to get the Finder/Dock icon;
    # --console-app opts back into a bare binary.  The .app still logs to the
    # terminal when its inner binary is launched from a shell, and it
    # auto-opens the browser, so hiding the console on a Finder double-click is
    # an acceptable trade.  Windows/Linux keep the console by default.
    mac_app = IS_MACOS and not args.console_app
    windowed = args.windowed or mac_app

    pyi_args = [
        shim,
        "--name", exe_name,
        "--noconfirm",
        "--onedir" if args.onedir else "--onefile",
        "--windowed" if windowed else "--console",
        "--paths", ROOT,                       # so `sw2robot` imports at build
        # bundle the editor page at the path WEB_DIR expects (HERE/web)
        "--add-data", f"{web}{os.pathsep}sw2robot/editor/web",
        # grab lazily / dynamically imported package code (incl. _vendor.rc_config)
        "--collect-submodules", "sw2robot",
        # bundle sw2robot's dist-info so importlib.metadata.version("sw2robot")
        # works in the frozen exe -- that is how sw2robot.__version__ (the
        # self-update check's "current version") is resolved at runtime
        "--copy-metadata", "sw2robot",
        # data + compiled bits these libraries load at runtime
        "--collect-all", "trimesh",
        "--collect-all", "pydantic",
        "--collect-all", "pydantic_core",
        # pycollada ships its COLLADA XSD under collada/resources/*.xml and
        # reads it via importlib.resources at .dae export time -- without the
        # DATA files the ROS-package (.dae) export dies with FileNotFoundError
        "--collect-all", "collada",
        # trimesh imports these LAZILY for mesh load / convert (3dxml parse,
        # dae/stl export); PyInstaller's static scan of trimesh misses them, so
        # a base (no-ui) exe dies with ModuleNotFoundError at export time.  The
        # ui build gets them transitively via skrobot -- name them so EVERY
        # build bundles them (their hooks then pull the needed bits).
        "--collect-all", "networkx",
        "--collect-all", "scipy",
        "--distpath", os.path.join(ROOT, "dist"),
        "--workpath", os.path.join(build_dir, "work"),
        "--specpath", build_dir,
    ]
    # The SolidWorks/COM glue (makepy gen_py redirect + the pywin32 hidden
    # imports PyInstaller's static scan misses) only exists, and is only needed,
    # on Windows.  On macOS/Linux pywin32 isn't installed, so emitting these
    # would just produce missing-module warnings for a code path that can never
    # run (no SolidWorks/COM there) -- skip them.
    if IS_WINDOWS:
        rthook = _write(os.path.join(build_dir, "rthook_win32com.py"), RTHOOK)
        pyi_args += ["--runtime-hook", rthook]
        for h in WIN32_HIDDEN:
            pyi_args += ["--hidden-import", h]

    # Embed the app icon.  Windows uses the committed .ico; macOS wants a .icns
    # (PyInstaller rejects a .ico there) and only shows it on the windowed .app.
    # Linux ELF binaries carry no embedded icon (it lives in a .desktop file),
    # so there is nothing to attach.  --icon is always honoured if given.
    if args.icon:
        icon = args.icon
    elif IS_WINDOWS:
        icon = os.path.join(ROOT, "assets", "icon.ico")
    elif IS_MACOS:
        icon = os.path.join(ROOT, "assets", "icon.icns")
    else:
        icon = None
    if icon and os.path.isfile(icon):
        pyi_args += ["--icon", icon]
    elif args.icon:
        print(f"WARNING: --icon {icon} not found; building without an icon.",
              file=sys.stderr)

    excludes = list(BASE_EXCLUDES)
    # Default is the full-feature build; --lean drops the optional backends,
    # --with-viser adds the standalone GUI on top.
    wanted = [] if args.lean else list(FULL_FEATURE_PACKAGES)
    if args.with_viser:
        wanted += STANDALONE_UI_PACKAGES
    # Only --collect-all what is actually installed.  A requested-but-missing
    # backend is reported LOUDLY (never silently dropped) so a "full" exe that is
    # in fact missing a feature is visible at build time, not at the user's first
    # click -- they cannot pip-install into a frozen binary to recover.
    include = [p for p in wanted if importlib.util.find_spec(p) is not None]
    missing = [p for p in wanted if p not in include]
    for p in missing:
        print(f"WARNING: '{p}' is not installed -> NOT bundled; this exe will "
              f"lack that feature.  `pip install` it before building (or pass "
              f"--lean to build a base exe on purpose).", file=sys.stderr)
    for p in include:
        pyi_args += ["--collect-all", p]
    excludes += [p for p in ALL_OPTIONAL_PACKAGES if p not in include]
    for e in excludes:
        pyi_args += ["--exclude-module", e]

    if args.clean:
        pyi_args.append("--clean")

    print("PyInstaller args:\n  " + " ".join(pyi_args) + "\n")
    pyi.run(pyi_args)

    # Output naming: a windowed macOS build is a .app bundle; Windows onefile
    # adds .exe; macOS console / Linux binaries have no extension.
    if mac_app:
        suffix = ".app"
    elif IS_WINDOWS and not args.onedir:
        suffix = ".exe"
    else:
        suffix = ""
    out = os.path.join(ROOT, "dist", exe_name + suffix)
    print(f"\nBuilt: {out}")
    if args.target == "web":
        if mac_app:
            # the runnable binary lives inside the bundle; this is also how you
            # see the server log/URL (a Finder double-click hides the console).
            invoke = f"./{exe_name}.app/Contents/MacOS/{exe_name}"
            sep = "/"
        elif IS_WINDOWS:
            invoke = f"{exe_name}{suffix}"
            sep = "\\"
        else:
            invoke = f"./{exe_name}"
            sep = "/"
        print("Run it like the module:  "
              f"{invoke} output{sep}<your_package> --port 8090")
    if IS_WINDOWS:
        print("NOTE: the target machine still needs SolidWorks installed for "
              "the extract step; view/edit/build/export work without it.")
    else:
        print("NOTE: the SolidWorks 'extract' step is Windows-only; this "
              "build does view/edit/build/export, incl. URDF-input editing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
