#!/usr/bin/env python
"""Freeze sw2robot into a standalone Windows .exe with PyInstaller.

Why PyInstaller: this app stacks pywin32 COM (SolidWorks), numpy, trimesh and
pydantic (compiled pydantic_core) -- PyInstaller ships working hooks for all of
them, which Nuitka / cx_Freeze do not out of the box.

Run it through uv so PyInstaller is available without polluting the project env::

    uv run --with pyinstaller python build_exe.py            # web editor, one-file
    uv run --with pyinstaller python build_exe.py --target export
    uv run --with pyinstaller python build_exe.py --onedir   # faster start, a folder
    uv run --with pyinstaller python build_exe.py --with-ui  # + collision/auto-limits

Targets (entry points, mirroring [project.scripts] in pyproject.toml):
    web     sw2robot-web  -> the browser editor server (default; does
                             extract + build + edit + export + view)
    export  sw2urdf       -> the extract+build CLI
    cli     sw2robot      -> the headless build/edit/export CLI

The .exe still needs SolidWorks INSTALLED on the target machine -- it drives
SolidWorks over COM; it does not (and cannot) embed it.  The makepy typelib
wrappers are generated on first extract into %TEMP%\\sw2robot_gen_py (see the
runtime hook below), so no COM cache has to be pre-baked into the bundle.
"""
from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))

# entry-point shims: PyInstaller wants a script, not a ``module:func`` spec, so
# we generate a tiny launcher that imports the package entry and calls main().
TARGETS = {
    "web":    ("sw2robot-web", "sw2robot.editor.webserver"),
    "export": ("sw2urdf",      "sw2robot.exporter.export"),
    "cli":    ("sw2robot",     "sw2robot.editor.cli"),
}

# pywin32 pieces PyInstaller's static analysis misses (COM + the makepy code
# generator that runs at extract time).
WIN32_HIDDEN = [
    "pythoncom", "pywintypes",
    "win32com", "win32com.client", "win32com.client.gencache",
    "win32com.client.makepy", "win32com.client.genpy",
    "win32com.client.build", "win32com.client.dynamic",
    "win32api", "win32con", "win32timezone",
]

# the optional ``ui`` extra.  The WEB editor's live self-collision + auto
# joint-limit sweep need skrobot + fcl; only the STANDALONE viser GUI needs
# viser.  Split so the web exe can bundle just the former (--editor-ui) without
# dragging in viser's web-client assets.  All excluded by default (small exe).
EDITOR_UI_PACKAGES = ["skrobot", "fcl"]
STANDALONE_UI_PACKAGES = ["viser"]
UI_PACKAGES = EDITOR_UI_PACKAGES + STANDALONE_UI_PACKAGES
# never needed at runtime -- dropping them shaves size / avoids hook noise
BASE_EXCLUDES = ["tkinter", "matplotlib", "pytest", "IPython", "notebook",
                 "jupyter", "PyQt5", "PyQt6", "PySide2", "PySide6"]

# Redirect pywin32's makepy/gencache output to a WRITABLE dir: inside a frozen
# bundle the default gen_py path is the read-only _MEIPASS, which makes
# EnsureModule/EnsureDispatch raise on the first SolidWorks extract.
RTHOOK = '''\
# AUTO-GENERATED by build_exe.py -- do not edit.
import os
import sys
import tempfile

if getattr(sys, "frozen", False):
    _gen = os.path.join(tempfile.gettempdir(), "sw2robot_gen_py")
    try:
        os.makedirs(_gen, exist_ok=True)
        import win32com
        win32com.__gen_path__ = _gen
        win32com.__build_path__ = _gen
        # if gen_py was already imported its __path__ still points at the old
        # (read-only) location -- repoint it so generated submodules are found
        if "win32com.gen_py" in sys.modules:
            sys.modules["win32com.gen_py"].__path__ = [_gen]
        import win32com.client.gencache as _gc
        _gc.is_readonly = False
        try:
            _gc.GetGeneratePath()      # create the package + __init__ if absent
        except Exception:
            pass
    except Exception:
        pass
'''


def _write(path: str, text: str) -> str:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--target", choices=list(TARGETS), default="web",
                    help="which entry point to freeze (default: web)")
    ap.add_argument("--onedir", action="store_true",
                    help="emit a folder instead of a single .exe (faster start, "
                         "more reliable for the COM/makepy path)")
    ap.add_argument("--with-ui", action="store_true",
                    help="bundle the full ui extra (skrobot/fcl/viser)")
    ap.add_argument("--editor-ui", action="store_true",
                    help="bundle just skrobot+fcl (web editor's live "
                         "self-collision + auto joint limits) WITHOUT the "
                         "standalone viser GUI -- lighter than --with-ui")
    ap.add_argument("--windowed", action="store_true",
                    help="no console window (default keeps the console so the "
                         "server URL / logs are visible)")
    ap.add_argument("--name", default=None,
                    help="override the output .exe name")
    ap.add_argument("--icon", default=None,
                    help="path to a .ico for the exe "
                         "(default: assets/icon.ico if present)")
    ap.add_argument("--clean", action="store_true",
                    help="wipe the PyInstaller cache before building")
    args = ap.parse_args()

    try:
        import PyInstaller.__main__ as pyi
    except ModuleNotFoundError:
        print("PyInstaller is not installed in this interpreter.\n"
              "Run instead:\n"
              "    uv run --with pyinstaller python build_exe.py "
              + " ".join(sys.argv[1:]), file=sys.stderr)
        return 2

    exe_name, module = TARGETS[args.target]
    exe_name = args.name or exe_name

    build_dir = os.path.join(ROOT, "build", "_pyi")
    shim = _write(os.path.join(build_dir, f"_entry_{args.target}.py"),
                  f"from {module} import main\n\n"
                  f"if __name__ == '__main__':\n    main()\n")
    rthook = _write(os.path.join(build_dir, "rthook_win32com.py"), RTHOOK)

    web = os.path.join(ROOT, "sw2robot", "editor", "web", "index.html")

    pyi_args = [
        shim,
        "--name", exe_name,
        "--noconfirm",
        "--onedir" if args.onedir else "--onefile",
        "--windowed" if args.windowed else "--console",
        "--paths", ROOT,                       # so `sw2robot` imports at build
        "--runtime-hook", rthook,
        # bundle the editor page at the path WEB_DIR expects (HERE/web)
        "--add-data", f"{web}{os.pathsep}sw2robot/editor/web",
        # grab lazily / dynamically imported package code (incl. _vendor.rc_config)
        "--collect-submodules", "sw2robot",
        # data + compiled bits these libraries load at runtime
        "--collect-all", "trimesh",
        "--collect-all", "pydantic",
        "--collect-all", "pydantic_core",
        # pycollada ships its COLLADA XSD under collada/resources/*.xml and
        # reads it via importlib.resources at .dae export time -- without the
        # DATA files the ROS-package (.dae) export dies with FileNotFoundError
        "--collect-all", "collada",
        # trimesh imports these LAZILY for mesh load / convert (3dxml parse,
        # dae/stl export); PyInstaller's static scan of trimesh misses them, so
        # a base (no-ui) exe dies with ModuleNotFoundError at export time.  The
        # ui build gets them transitively via skrobot -- name them so EVERY
        # build bundles them (their hooks then pull the needed bits).
        "--collect-all", "networkx",
        "--collect-all", "scipy",
        "--distpath", os.path.join(ROOT, "dist"),
        "--workpath", os.path.join(build_dir, "work"),
        "--specpath", build_dir,
    ]
    # Embed the app icon.  Default to the committed assets/icon.ico so every
    # build is branded without extra flags.
    icon = args.icon or os.path.join(ROOT, "assets", "icon.ico")
    if os.path.isfile(icon):
        pyi_args += ["--icon", icon]
    elif args.icon:
        print(f"WARNING: --icon {icon} not found; building without an icon.",
              file=sys.stderr)

    for h in WIN32_HIDDEN:
        pyi_args += ["--hidden-import", h]

    excludes = list(BASE_EXCLUDES)
    if args.with_ui:
        include_ui = UI_PACKAGES
    elif args.editor_ui:
        include_ui = EDITOR_UI_PACKAGES
    else:
        include_ui = []
    for p in include_ui:
        pyi_args += ["--collect-all", p]
    excludes += [p for p in UI_PACKAGES if p not in include_ui]
    for e in excludes:
        pyi_args += ["--exclude-module", e]

    if args.clean:
        pyi_args.append("--clean")

    print("PyInstaller args:\n  " + " ".join(pyi_args) + "\n")
    pyi.run(pyi_args)

    out = os.path.join(ROOT, "dist",
                       exe_name if args.onedir else exe_name + ".exe")
    print(f"\nBuilt: {out}")
    if args.target == "web":
        print("Run it like the module:  "
              f"{exe_name}.exe output\\<your_package> --port 8090")
    print("NOTE: the target machine still needs SolidWorks installed for the "
          "extract step; view/edit/build/export work without it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
