"""
Imitation Learning configuration generators.

Generates configuration files for RL/IL training.
"""

from typing import Any


def generate_il_config(
    observation: dict[str, Any],
    action: dict[str, Any],
    joints: list[dict[str, Any]],
) -> str:
    """
    Generate Imitation Learning configuration YAML.

    Parameters
    ----------
    observation : dict
        Observation space configuration with:
        - includeJointPositions: bool
        - includeJointVelocities: bool
        - includeEndEffectorPose: bool
        - customObservations: list of custom observation names
    action : dict
        Action space configuration with:
        - actionType: 'joint_positions', 'joint_velocities', or 'end_effector_delta'
        - selectedJoints: list of joint names
        - actionScale: float multiplier for actions
    joints : list
        List of joint configurations for dimension calculation.

    Returns
    -------
    str
        YAML configuration content.
    """
    # Calculate dimensions
    actuated_joints = [j for j in joints if j.get("type") != "fixed"]
    n_joints = len(actuated_joints)

    obs_dim = 0
    if observation.get("includeJointPositions", True):
        obs_dim += n_joints
    if observation.get("includeJointVelocities", True):
        obs_dim += n_joints
    if observation.get("includeEndEffectorPose", False):
        obs_dim += 7  # position (3) + quaternion (4)

    custom_obs = observation.get("customObservations", [])
    obs_dim += len(custom_obs)

    action_joints = action.get("selectedJoints", [])
    action_dim = len(action_joints)

    lines = [
        "# Imitation Learning Configuration",
        "# Generated by Robot Compiler",
        "",
        "robot:",
        "  observation_space:",
        f"    dim: {obs_dim}",
        f"    include_joint_positions: {str(observation.get('includeJointPositions', True)).lower()}",
        f"    include_joint_velocities: {str(observation.get('includeJointVelocities', True)).lower()}",
        f"    include_end_effector_pose: {str(observation.get('includeEndEffectorPose', False)).lower()}",
    ]

    if custom_obs:
        lines.append("    custom_observations:")
        for obs in custom_obs:
            lines.append(f"      - {obs}")

    lines.extend(
        [
            "",
            "  action_space:",
            f"    dim: {action_dim}",
            f"    type: {action.get('actionType', 'joint_positions')}",
            f"    scale: {action.get('actionScale', 1.0)}",
            "    joints:",
        ]
    )

    for joint in action_joints:
        lines.append(f"      - {joint}")

    # Add joint limits for reference
    lines.extend(
        [
            "",
            "  joint_limits:",
        ]
    )

    for joint in actuated_joints:
        if joint["name"] in action_joints:
            lines.append(f"    {joint['name']}:")
            lines.append(f"      lower: {joint.get('lowerLimit', 0.0)}")
            lines.append(f"      upper: {joint.get('upperLimit', 0.0)}")
            lines.append(f"      velocity: {joint.get('velocityLimit', 0.0)}")

    # Add training hints
    lines.extend(
        [
            "",
            "# Training Configuration",
            "training:",
            "  horizon: 1000",
            "  batch_size: 256",
            "  learning_rate: 3.0e-4",
            "  gamma: 0.99",
            "  clip_range: 0.2",
            "",
            "# Normalization",
            "normalization:",
            "  normalize_observations: true",
            "  normalize_rewards: true",
            "  clip_observations: 10.0",
        ]
    )

    return "\n".join(lines)
