"""
Servo mapping configuration generators.

Generates configuration files for joint-to-servo ID mapping.
"""

from typing import Any


def generate_servo_mapping_yaml(
    servo_mappings: list[dict[str, Any]],
) -> str:
    """
    Generate servo mapping YAML configuration.

    Parameters
    ----------
    servo_mappings : list
        List of servo mapping configurations with:
        - jointName: Joint name in URDF
        - servoId: Servo motor ID (0-255)
        - direction: 1 or -1
        - angleOffset: Angle offset in radians
        - minAngle: Minimum angle limit
        - maxAngle: Maximum angle limit

    Returns
    -------
    str
        YAML configuration content.
    """
    lines = [
        "# Servo Mapping Configuration",
        "# Generated by Robot Compiler",
        "#",
        "# Maps URDF joint names to physical servo motor IDs",
        "",
        "servo_mapping:",
    ]

    for mapping in servo_mappings:
        joint_name = mapping.get("jointName", "unknown")
        servo_id = mapping.get("servoId")

        if servo_id is None:
            continue  # Skip joints without servo IDs

        direction = mapping.get("direction", 1)
        offset = mapping.get("angleOffset", 0.0)
        min_angle = mapping.get("minAngle", 0.0)
        max_angle = mapping.get("maxAngle", 0.0)

        lines.extend(
            [
                f"  {joint_name}:",
                f"    servo_id: {servo_id}",
                f"    direction: {direction}",
                f"    angle_offset: {offset}",
                f"    min_angle: {min_angle}",
                f"    max_angle: {max_angle}",
            ]
        )

    return "\n".join(lines)


def generate_servo_mapping_json(
    servo_mappings: list[dict[str, Any]],
) -> dict[str, Any]:
    """
    Generate servo mapping as a JSON-compatible dictionary.

    Parameters
    ----------
    servo_mappings : list
        List of servo mapping configurations.

    Returns
    -------
    dict
        JSON-compatible dictionary with servo mappings.
    """
    result = {}

    for mapping in servo_mappings:
        joint_name = mapping.get("jointName", "unknown")
        servo_id = mapping.get("servoId")

        if servo_id is None:
            continue

        result[joint_name] = {
            "servo_id": servo_id,
            "direction": mapping.get("direction", 1),
            "angle_offset": mapping.get("angleOffset", 0.0),
            "min_angle": mapping.get("minAngle", 0.0),
            "max_angle": mapping.get("maxAngle", 0.0),
        }

    return {"servo_mapping": result}
